apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: foodgram
type: Opaque
stringData:
  POSTGRES_DB: foodgram
  POSTGRES_USER: foodgram_user
  POSTGRES_PASSWORD: foodgram_password