apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: foodgram
type: Opaque
data:
  SECRET_KEY: "WWMtQlA2cjVlenRMMXpBTW14ZlhmeGxVaGtfdHZZbWJxa0E3OUw4ekNEY01FTnZWN3RQd2dqcnk2T3FGaEFvdnlJ"